In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split  
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv('train.csv', usecols=['Age', 'Fare', 'Survived'])
df.sample(5)

     Survived   Age     Fare
480         0   9.0  46.9000
404         0  20.0   8.6625
109         1   NaN  24.1500
34          0  28.0  82.1708
262         0  52.0  79.6500

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Age       714 non-null    float64
 2   Fare      891 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 21.0 KB

In [6]:
df.describe()

         Survived         Age        Fare
count  891.000000  714.000000  891.000000
mean     0.383838   29.699118   32.204208
std      0.486592   14.526497   49.693429
min      0.000000    0.420000    0.000000
25%      0.000000   20.125000    7.910400
50%      0.000000   28.000000   14.454200
75%      1.000000   38.000000   31.000000
max      1.000000   80.000000  512.329200

In [7]:
x= df.drop(columns=['Survived'])
y = df['Survived']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [9]:
x_train

      Age     Fare
140   NaN  15.2458
439  31.0  10.5000
817  31.0  37.0042
378  20.0   4.0125
491  21.0   7.2500
..    ...      ...
835  39.0  83.1583
192  19.0   7.8542
629   NaN   7.7333
559  36.0  17.4000
684  60.0  39.0000

[712 rows x 2 columns]

In [10]:
imputer = SimpleImputer()

In [11]:
x_train_trf = imputer.fit_transform(x_train)
x_test_trf = imputer.transform(x_test)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.impute import MissingIndicator

In [13]:
clf = LogisticRegression()

In [14]:
clf.fit(x_train_trf, y_train)
y_pred = clf.predict(x_test_trf)

In [15]:
accuracy_score(y_test, y_pred)

0.6983240223463687

In [17]:
mi = MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [20]:
mi.features_

array([0])

In [21]:
x_train_missing = mi.transform(x_train)
x_test_missing = mi.transform(x_test)

In [22]:
x_train['Age_na'] = x_train_missing
x_test['Age_na'] = x_test_missing

In [23]:
x_train

      Age     Fare  Age_na
140   NaN  15.2458    True
439  31.0  10.5000   False
817  31.0  37.0042   False
378  20.0   4.0125   False
491  21.0   7.2500   False
..    ...      ...     ...
835  39.0  83.1583   False
192  19.0   7.8542   False
629   NaN   7.7333    True
559  36.0  17.4000   False
684  60.0  39.0000   False

[712 rows x 3 columns]

In [25]:
imputer = SimpleImputer()
x_train_trf1 = imputer.fit_transform(x_train)
x_test_trf1 = imputer.transform(x_test)

In [27]:
clf = LogisticRegression()
clf.fit(x_train_trf1, y_train)
y_pred2 = clf.predict(x_test_trf1)

In [28]:
accuracy_score(y_test, y_pred2)

0.6871508379888268