In [1]:
import pandas as pd 
import numpy as np

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.sample(5)

           date  product_id  city_id  orders
464  2018-09-26        4895       29       1
820  2019-07-27        7239       22       2
525  2019-06-13        2249       20       2
914  2019-08-12        4908       14       4
85   2019-11-13        5288       18       7

In [4]:
time.sample(5)

                    date                                                msg
116  2014-04-05 23:51:00  Здам комнату одинокой дев. или женщине не доро...
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
824  2012-04-05 23:41:00    ПАРЕНЬ 30Л ПОЗНАК С ДЕВУШКОЙ ДЛЯ С/О 0938903541
984  2013-11-28 00:26:00                  Анжела будет рада позн с М для со
975  2013-10-07 00:54:00                                 Отношения Кристина

In [6]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [7]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

working with dates

In [8]:
date['date']=pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

1) extrat the year

In [11]:
date['date_year']= date['date'].dt.year

In [13]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

2) extract month

In [14]:
date['date_month']= date['date'].dt.month

In [15]:
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
815 2019-12-08        3659       20       4       2019          12
290 2018-12-05        4254       16      37       2018          12
541 2018-12-10        2457        3      13       2018          12
639 2019-11-04        7198       13       1       2019          11
91  2018-09-18         923       13       1       2018           9

In [16]:
date['date_month_name']=  date['date'].dt.month_name()

In [17]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name
74,2019-11-13,2199,14,2,2019,11,November
912,2019-08-05,7140,18,37,2019,8,August
249,2018-12-14,2265,25,1,2018,12,December
700,2019-10-23,2669,25,20,2019,10,October
946,2018-11-10,6309,29,11,2018,11,November

3) extract days

In [18]:
date['days'] = date['date'].dt.day

In [19]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days
678,2018-10-02,6293,14,32,2018,10,October,2
875,2018-11-01,4495,28,1,2018,11,November,1
130,2019-07-12,2242,8,2,2019,7,July,12
926,2019-07-07,6640,26,48,2019,7,July,7
306,2019-08-01,820,30,2,2019,8,August,1

In [26]:
#daye of week
date['day_of_week']= date['date'].dt.dayofweek

In [29]:
date.head(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [31]:
#fdaye of week name
date['day_of_week_name']= date['date'].dt.day_name()

In [32]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_of_week,day_of_week_name
758,2019-01-03,2306,14,2,2019,1,January,3,3,Thursday
718,2018-10-09,2639,28,1,2018,10,October,9,1,Tuesday
987,2018-12-25,27,10,41,2018,12,December,25,1,Tuesday
888,2019-11-09,6850,1,2,2019,11,November,9,5,Saturday
467,2018-07-14,1114,13,90,2018,7,July,14,5,Saturday

In [33]:
# is weekwnd ??
date['is_weekend']= np.where(date['day_of_week_name'].isin(['Saturday', 'Sunday']), 1, 0)

In [34]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_of_week,day_of_week_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

4) extarct week of the year

In [ ]:
date['week_of_year']= date['date'].dt.isocalendar().week

In [41]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_of_week,day_of_week_name,is_weekend,week_of_year
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

5) extracrt quater

In [42]:
date['quater'] = date['date'].dt.quarter

In [44]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_of_week,day_of_week_name,is_weekend,week_of_year,quater
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

6) extract semisters

In [46]:
date['semester']= np.where(date['quater'].isin([1,2]),1,2)

In [47]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_of_week,day_of_week_name,is_weekend,week_of_year,quater,semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

7) extract time elapsed between dates

In [48]:
import datetime

today = datetime.datetime.today()

In [49]:
today

datetime.datetime(2026, 4, 22, 18, 10, 38, 759226)

In [50]:
today - date['date']

0     2325 days 18:10:38.759226
1     2807 days 18:10:38.759226
2     2738 days 18:10:38.759226
3     2440 days 18:10:38.759226
4     2663 days 18:10:38.759226
                 ...
995   2753 days 18:10:38.759226
996   2694 days 18:10:38.759226
997   2542 days 18:10:38.759226
998   2607 days 18:10:38.759226
999   2381 days 18:10:38.759226
Name: date, Length: 1000, dtype: timedelta64[us]

In [51]:
(today- date['date']).dt.days

0      2325
1      2807
2      2738
3      2440
4      2663
       ...
995    2753
996    2694
997    2542
998    2607
999    2381
Name: date, Length: 1000, dtype: int64

In [55]:
#months passed
np.round((today - date['date'])/np.timedelta64(1,'D')/30.44, 0) # here we are using this [/30.44] bcz it doesnt give us the exact month so we are using this to get the approximate month

0      76.0
1      92.0
2      90.0
3      80.0
4      88.0
       ...
995    90.0
996    89.0
997    84.0
998    86.0
999    78.0
Name: date, Length: 1000, dtype: float64

In [56]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [57]:
time['date'] = pd.to_datetime(time['date'])

In [59]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [60]:
time['hour'] = time['date'].dt.hour

In [61]:
time['min'] = time['date'].dt.minute

In [62]:
time['sec'] = time['date'].dt.second

In [63]:
time.sample(5)

,date,msg,hour,min,sec
213,2016-12-09 23:20:00,Dlj vzrosloi D. 067 148 98 58.,23,20,0
39,2016-05-07 00:07:00,Муж.45.женат ищу дев.женщину для встреч.жду ва...,0,7,0
490,2014-08-18 22:55:00,ПАРЕНЬ ПОЗНАКОМЛЮСЬ С НОРМАЛЬНОЙ ДЕВУШКОЙ.18-2...,22,55,0
636,2015-07-09 00:58:00,. Мне 39. Поцелую взрослой женщине. Жду смс фо...,0,58,0
728,2013-03-03 01:06:00,МУЖЧ И ЖЕНЩ НУЖЕН СМС 097 536 07 21,1,6,0

In [64]:
time['time'] = time['date'].dt.time

In [65]:
time.sample(5)

,date,msg,hour,min,sec,time
95,2015-01-02 00:46:00,Привет я рая из рая,0,46,0,00:46:00
218,2013-01-23 23:24:00,м 44 ищет друга до 50л для встреч с местом из ...,23,24,0,23:24:00
912,2013-04-28 01:10:00,симпатичный парень ищет нескромну милашку 8093...,1,10,0,01:10:00
621,2016-01-17 00:19:00,Катя я тебе люблю. Ваня,0,19,0,00:19:00
980,2013-03-16 00:42:00,Юрка не молчи!!!!!,0,42,0,00:42:00

In [66]:
today - time['date']

0     4511 days 17:20:38.759226
1     4375 days 18:30:38.759226
2     4861 days 17:49:38.759226
3     4163 days 17:39:38.759226
4     4560 days 18:59:38.759226
                 ...
995   5150 days 17:20:38.759226
996   4471 days 18:56:38.759226
997   4936 days 18:33:38.759226
998   5052 days 18:36:38.759226
999   4324 days 18:45:38.759226
Name: date, Length: 1000, dtype: timedelta64[us]

In [67]:
# in seconds
(today - time['date'])/np.timedelta64(1,'s')

0      3.898128e+08
1      3.780666e+08
2      4.200546e+08
3      3.597468e+08
4      3.940524e+08
           ...
995    4.450224e+08
996    3.863626e+08
997    4.265372e+08
998    4.365598e+08
999    3.736611e+08
Name: date, Length: 1000, dtype: float64

In [68]:
# in minutes
(today - time['date'])/ np.timedelta64(1, 'm')

0      6.496881e+06
1      6.301111e+06
2      7.000910e+06
3      5.995780e+06
4      6.567540e+06
           ...
995    7.417041e+06
996    6.439377e+06
997    7.108954e+06
998    7.275997e+06
999    6.227686e+06
Name: date, Length: 1000, dtype: float64

In [69]:
# in hours

(today - time['date'])/ np.timedelta64(1,'h')

0      108281.344100
1      105018.510766
2      116681.827433
3       99929.660766
4      109458.994100
           ...
995    123617.344100
996    107322.944100
997    118482.560766
998    121266.610766
999    103794.760766
Name: date, Length: 1000, dtype: float64